package com.yanhuo.sign.dal.model;

import java.io.Serializable;
import java.util.Date;

public class Course implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cource_id
     *
     * @mbggenerated
     */
    private Long courceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cource_name
     *
     * @mbggenerated
     */
    private String courceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cource_time
     *
     * @mbggenerated
     */
    private Date courceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cource_location
     *
     * @mbggenerated
     */
    private String courceLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.teacher_id
     *
     * @mbggenerated
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.class
     *
     * @mbggenerated
     */
    private String class;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cource_account
     *
     * @mbggenerated
     */
    private Integer courceAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cource_id
     *
     * @return the value of course.cource_id
     *
     * @mbggenerated
     */
    public Long getCourceId() {
        return courceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cource_id
     *
     * @param courceId the value for course.cource_id
     *
     * @mbggenerated
     */
    public void setCourceId(Long courceId) {
        this.courceId = courceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cource_name
     *
     * @return the value of course.cource_name
     *
     * @mbggenerated
     */
    public String getCourceName() {
        return courceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cource_name
     *
     * @param courceName the value for course.cource_name
     *
     * @mbggenerated
     */
    public void setCourceName(String courceName) {
        this.courceName = courceName == null ? null : courceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cource_time
     *
     * @return the value of course.cource_time
     *
     * @mbggenerated
     */
    public Date getCourceTime() {
        return courceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cource_time
     *
     * @param courceTime the value for course.cource_time
     *
     * @mbggenerated
     */
    public void setCourceTime(Date courceTime) {
        this.courceTime = courceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cource_location
     *
     * @return the value of course.cource_location
     *
     * @mbggenerated
     */
    public String getCourceLocation() {
        return courceLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cource_location
     *
     * @param courceLocation the value for course.cource_location
     *
     * @mbggenerated
     */
    public void setCourceLocation(String courceLocation) {
        this.courceLocation = courceLocation == null ? null : courceLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_id
     *
     * @return the value of course.teacher_id
     *
     * @mbggenerated
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_id
     *
     * @param teacherId the value for course.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.class
     *
     * @return the value of course.class
     *
     * @mbggenerated
     */
    public String getClass() {
        return class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.class
     *
     * @param class the value for course.class
     *
     * @mbggenerated
     */
    public void setClass(String class) {
        this.class = class == null ? null : class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cource_account
     *
     * @return the value of course.cource_account
     *
     * @mbggenerated
     */
    public Integer getCourceAccount() {
        return courceAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cource_account
     *
     * @param courceAccount the value for course.cource_account
     *
     * @mbggenerated
     */
    public void setCourceAccount(Integer courceAccount) {
        this.courceAccount = courceAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", courceId=").append(courceId);
        sb.append(", courceName=").append(courceName);
        sb.append(", courceTime=").append(courceTime);
        sb.append(", courceLocation=").append(courceLocation);
        sb.append(", teacherId=").append(teacherId);
        sb.append(", class=").append(class);
        sb.append(", courceAccount=").append(courceAccount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}