package com.yanhuo.sign.dal.model;

import java.io.Serializable;

public class Manager implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_id
     *
     * @mbggenerated
     */
    private Long managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_pwd
     *
     * @mbggenerated
     */
    private Integer managerPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.manager_name
     *
     * @mbggenerated
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table manager
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_id
     *
     * @return the value of manager.manager_id
     *
     * @mbggenerated
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_id
     *
     * @param managerId the value for manager.manager_id
     *
     * @mbggenerated
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_pwd
     *
     * @return the value of manager.manager_pwd
     *
     * @mbggenerated
     */
    public Integer getManagerPwd() {
        return managerPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_pwd
     *
     * @param managerPwd the value for manager.manager_pwd
     *
     * @mbggenerated
     */
    public void setManagerPwd(Integer managerPwd) {
        this.managerPwd = managerPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.manager_name
     *
     * @return the value of manager.manager_name
     *
     * @mbggenerated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.manager_name
     *
     * @param managerName the value for manager.manager_name
     *
     * @mbggenerated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", managerId=").append(managerId);
        sb.append(", managerPwd=").append(managerPwd);
        sb.append(", managerName=").append(managerName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}