package com.yanhuo.sign.dal.model;

import java.io.Serializable;
import java.util.Date;

public class Sign implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_id
     *
     * @mbggenerated
     */
    private Long signId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_time
     *
     * @mbggenerated
     */
    private Date signTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_account
     *
     * @mbggenerated
     */
    private Integer signAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.student_id
     *
     * @mbggenerated
     */
    private Long studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.is_sign
     *
     * @mbggenerated
     */
    private Integer isSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_id
     *
     * @return the value of sign.sign_id
     *
     * @mbggenerated
     */
    public Long getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_id
     *
     * @param signId the value for sign.sign_id
     *
     * @mbggenerated
     */
    public void setSignId(Long signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_time
     *
     * @return the value of sign.sign_time
     *
     * @mbggenerated
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_time
     *
     * @param signTime the value for sign.sign_time
     *
     * @mbggenerated
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_account
     *
     * @return the value of sign.sign_account
     *
     * @mbggenerated
     */
    public Integer getSignAccount() {
        return signAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_account
     *
     * @param signAccount the value for sign.sign_account
     *
     * @mbggenerated
     */
    public void setSignAccount(Integer signAccount) {
        this.signAccount = signAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.student_id
     *
     * @return the value of sign.student_id
     *
     * @mbggenerated
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.student_id
     *
     * @param studentId the value for sign.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.is_sign
     *
     * @return the value of sign.is_sign
     *
     * @mbggenerated
     */
    public Integer getIsSign() {
        return isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.is_sign
     *
     * @param isSign the value for sign.is_sign
     *
     * @mbggenerated
     */
    public void setIsSign(Integer isSign) {
        this.isSign = isSign;
    }

    public Sign(Long signId, Date signTime, Integer signAccount, Long studentId, Integer isSign) {
        this.signId = signId;
        this.signTime = signTime;
        this.signAccount = signAccount;
        this.studentId = studentId;
        this.isSign = isSign;
    }

    public Sign() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign
     *
     * @mbggenerated
     */


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", signId=").append(signId);
        sb.append(", signTime=").append(signTime);
        sb.append(", signAccount=").append(signAccount);
        sb.append(", studentId=").append(studentId);
        sb.append(", isSign=").append(isSign);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}