package com.yanhuo.sign.dal.model;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbggenerated
     */
    private Long studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class
     *
     * @mbggenerated
     */
    private String class;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.institute
     *
     * @mbggenerated
     */
    private String institute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_gender
     *
     * @mbggenerated
     */
    private String studentGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.continous_account
     *
     * @mbggenerated
     */
    private Integer continousAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbggenerated
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class
     *
     * @return the value of student.class
     *
     * @mbggenerated
     */
    public String getClass() {
        return class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class
     *
     * @param class the value for student.class
     *
     * @mbggenerated
     */
    public void setClass(String class) {
        this.class = class == null ? null : class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.institute
     *
     * @return the value of student.institute
     *
     * @mbggenerated
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.institute
     *
     * @param institute the value for student.institute
     *
     * @mbggenerated
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.open_id
     *
     * @return the value of student.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.open_id
     *
     * @param openId the value for student.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_gender
     *
     * @return the value of student.student_gender
     *
     * @mbggenerated
     */
    public String getStudentGender() {
        return studentGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_gender
     *
     * @param studentGender the value for student.student_gender
     *
     * @mbggenerated
     */
    public void setStudentGender(String studentGender) {
        this.studentGender = studentGender == null ? null : studentGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.continous_account
     *
     * @return the value of student.continous_account
     *
     * @mbggenerated
     */
    public Integer getContinousAccount() {
        return continousAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.continous_account
     *
     * @param continousAccount the value for student.continous_account
     *
     * @mbggenerated
     */
    public void setContinousAccount(Integer continousAccount) {
        this.continousAccount = continousAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentId=").append(studentId);
        sb.append(", studentName=").append(studentName);
        sb.append(", class=").append(class);
        sb.append(", institute=").append(institute);
        sb.append(", openId=").append(openId);
        sb.append(", studentGender=").append(studentGender);
        sb.append(", continousAccount=").append(continousAccount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}